# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_capital.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("simplistica/png/64x64/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = GraphicsLayoutWidget(self.widget)
        self.graphicsView.setMinimumSize(QtCore.QSize(550, 0))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditSticker = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSticker.sizePolicy().hasHeightForWidth())
        self.lineEditSticker.setSizePolicy(sizePolicy)
        self.lineEditSticker.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEditSticker.setObjectName("lineEditSticker")
        self.gridLayout.addWidget(self.lineEditSticker, 0, 0, 1, 1)
        self.buttonSwitch = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSwitch.sizePolicy().hasHeightForWidth())
        self.buttonSwitch.setSizePolicy(sizePolicy)
        self.buttonSwitch.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonSwitch.setFont(font)
        self.buttonSwitch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonSwitch.setObjectName("buttonSwitch")
        self.gridLayout.addWidget(self.buttonSwitch, 0, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 2)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menuBar)
        self.actionCollect = QtWidgets.QAction(MainWindow)
        self.actionCollect.setObjectName("actionCollect")
        self.actionSharesCsv = QtWidgets.QAction(MainWindow)
        self.actionSharesCsv.setObjectName("actionSharesCsv")
        self.actionBlocksCsv = QtWidgets.QAction(MainWindow)
        self.actionBlocksCsv.setObjectName("actionBlocksCsv")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAutoFix = QtWidgets.QAction(MainWindow)
        self.actionAutoFix.setObjectName("actionAutoFix")
        self.actionBlocksFolders = QtWidgets.QAction(MainWindow)
        self.actionBlocksFolders.setObjectName("actionBlocksFolders")
        self.menuTools.addAction(self.actionOpen)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSharesCsv)
        self.menuTools.addAction(self.actionBlocksCsv)
        self.menuTools.addAction(self.actionBlocksFolders)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCollect)
        self.menuTools.addAction(self.actionAutoFix)
        self.menuBar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CapitalData"))
        self.buttonSwitch.setText(_translate("MainWindow", "个股/板块"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionCollect.setText(_translate("MainWindow", "Collect Data"))
        self.actionSharesCsv.setText(_translate("MainWindow", "tickers_dl.csv"))
        self.actionBlocksCsv.setText(_translate("MainWindow", "blocks_dl.csv"))
        self.actionOpen.setText(_translate("MainWindow", "Open File"))
        self.actionAutoFix.setText(_translate("MainWindow", "Auto Fix"))
        self.actionBlocksFolders.setText(_translate("MainWindow", "Blocks Folder"))


from pyqtgraph import GraphicsLayoutWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
